### ISSUE TITLE
sfileoutput is not saving the material model correctly

### ISSUE THREAD

**Issue by jf-huang** [geodynamics/sw4#173]
Hi, I was trying to use the sfileoutput command to save my material model but found the resultant sfile may not have been written correctly as it actually is in SW4. Below are two shear wave velocity plots at the same cross-section of the domain plotted based on the image file and the sfile, respectively. 
![image](https://user-images.githubusercontent.com/44045796/226775363-572a66a0-c89b-48ea-88a2-52c1a5511a81.png)
As can be seen, Vs is quite different in the domain, and there are some singularity spots in the sfile plot. In fact, **some of the values saved in the sfile are NaNs and negative values (for all properties including 'Cp', 'Cs', 'Qp', 'Qs', 'Rho')**, while the command line output by SW4 shows all values are positive and within the expected range, and the time-stepping phase can be finished successfully. This means the issue likely happens only when writing out the sfile. Although not confirmed, this behavior may have led to segmentation faults that I have encountered sometimes when saving the sfile. I am attaching a small test model that replicates this issue.

[testModel.zip](https://github.com/geodynamics/sw4/files/11035364/testModel.zip)

**Comment by houjun** [comment]
@jf-huang, this should be fixed with the latest developer branch (#174), please try again.

**Comment by jf-huang** [comment]
Hi Houjun @houjun, thanks for the quick response! I rerun the model with the latest executable you provided and the issue seems partially resolved while there are still some offsets in the layer properties (compared to the image output), as shown below:
![image](https://user-images.githubusercontent.com/44045796/227069884-eda5e0a5-9773-4c8d-811e-175e20beabfd.png)

**Comment by houjun** [comment]
should be fixed with #177

**Comment by jf-huang** [comment]
I confirm this is fixed now, thanks @houjun !
